// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeAWfccSW9oSnsjwsl4iM2MB6W90g6zW4',
    appId: '1:693716627139:ios:a96a0bfe48bea30b03fc76',
    messagingSenderId: '693716627139',
    projectId: 'authforapp1',
    storageBucket: 'authforapp1.firebasestorage.app',
    iosBundleId: 'com.example.sceneapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmrxajr5o0_dIIDU9wXF9w7j_LrlhTSS4',
    appId: '1:693716627139:web:e4847b8e955c340603fc76',
    messagingSenderId: '693716627139',
    projectId: 'authforapp1',
    authDomain: 'authforapp1.firebaseapp.com',
    storageBucket: 'authforapp1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeAWfccSW9oSnsjwsl4iM2MB6W90g6zW4',
    appId: '1:693716627139:ios:a96a0bfe48bea30b03fc76',
    messagingSenderId: '693716627139',
    projectId: 'authforapp1',
    storageBucket: 'authforapp1.firebasestorage.app',
    iosBundleId: 'com.example.sceneapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz_wTRhRCEw59t-WyskBTLrQdKTbm0jdE',
    appId: '1:693716627139:android:5f14cfc3e6498ad803fc76',
    messagingSenderId: '693716627139',
    projectId: 'authforapp1',
    storageBucket: 'authforapp1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmrxajr5o0_dIIDU9wXF9w7j_LrlhTSS4',
    appId: '1:693716627139:web:e3ebc0b189bf918103fc76',
    messagingSenderId: '693716627139',
    projectId: 'authforapp1',
    authDomain: 'authforapp1.firebaseapp.com',
    storageBucket: 'authforapp1.firebasestorage.app',
  );

}